# Generated by Django 2.2.7 on 2019-11-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineUser',
            fields=[
                ('account', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=27)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformatin',
            fields=[
                ('name', models.CharField(default='赵四', max_length=20)),
                ('number', models.CharField(default=123456789, max_length=9, primary_key=True, serialize=False)),
                ('sex', models.CharField(default='男', max_length=4)),
                ('birth', models.CharField(default='string', max_length=10)),
                ('college', models.CharField(default='SOME STRING', max_length=30)),
                ('major', models.CharField(default='SOME STRING', max_length=30)),
                ('grade', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('account', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=20)),
            ],
        ),
    ]
